application:
  currency_pairs:
    - EUR/USD
    - USD/RUB
  timeframe:
    - 1
    - 5
    - 15
    - 30
    - 60


server:
  port: 8082
  error:
    include-message: always
    include-stacktrace: never

